### ISSUE TITLE
Index for Matching People to citation searches

### ISSUE THREAD

**Issue by qjhart** [ucd-library/vessel#11]
When users search for words that are found in citations, we need to respond with associated people as well.  @jrmerz suggested that the elastic search best practice for this is probably to create a new index that is researcher based and indices all citations.  I suppose that this could also just be added to the current people card, since realistically the scores from the citation should be incorporated with the scores from the persons page as well. @Vensberg has volunteered to help @jtyzzer with weights if that is needed.

**Comment by jrmerz** [comment]
This is currently using the following indexes which are calculated by the post-process.js class:

```
    "lastCitation.publication" : {
      "type" : "text"
    },

    "lastCitation.label" : {
      "type" : "text"
    },

    "_.top20Citation.publication" : {
      "type" : "text"
    },

    "_.top20Citation.label" : {
      "type" : "text"
    }
```
