### ISSUE TITLE
Determine initial text indexes

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/vessel#3]
We need to determine
 - which fields we want to create text indexes on
 - what fields we want to use in default search (user just types into text box)
 - what the weights for each text indexes should be (default search).  Assume a normalized 1-10 value with default being 5. 

It's important to remember that ALL types will go into this schema, enabling universal search.  Though the 'default search' for the site will limit to a subset of types.  This issue is address the default search text fields and weights.

The current elastic search schema is here: https://github.com/ucd-library/vessel/blob/dev/es-indexer/lib/elastic-search/vivo.json
Any `property` with `type:text` or sub `fields` with `type:text` generate a text index.

Notes on multi index fields.  You can create default index as well as sub fields with additional indexes on the parent.  So in the example:

```
"hasSubjectArea.label" : {
      "type" : "keyword",
      "fields": {
        "text" : {
          "type" : "text",
          "analyzer": "autocomplete", 
          "search_analyzer": "autocomplete_search"
        }
      }
    }
```

`hasSubjectArea.label` is a keyword index (exact match facet), while `hasSubjectArea.label.text` is the text index on the `hasSubjectArea.label` property.

**Comment by jtyzzer** [comment]
https://docs.google.com/document/d/1GQ0LExoaA1Rp6i6mVYl5dYdoVle3qVp4R2-CgugE3lE/edit?usp=sharing

**Comment by jtyzzer** [comment]
| Search Type  | Field | Weight |
| --- | --- |---|
| People | Family name | 9 |
| People | Given name | 8 |
| People | hasContactInfo.title | 7 |
| People | Subject area | 6 |
| Works | DOI | 10 |
| Works | Title | 9 |
| Works | Abstract | 8 |
| Works | Journal title | 7 |
| Works | Subject area (person's)| 6 |
| Works | ISSN | 5 |
| Organizations | Name | 10 |
| Organizations | Work title | 7 |
| Organizations | Grant name | 6 |
| All | DOI | 10 |
| All | Family name | 9 |
| All | Given name | 8 |
| All | Subject area | 7 |
| All | Title | 6 |
| All | Journal title | 5 |
| All | Subject area (work's) | 5 |
| All | Abstract | 5 |

**Comment by jrmerz** [comment]
Add to works: Authorship -> hasName -> familyName for works
