### ISSUE TITLE
Implement initial text indexes on search

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/vessel#4]
https://github.com/ucd-library/vessel/issues/3 defines our initial set of text indexes.  These indexes and provided weights should be used when searching for the various vivo types.

**Comment by spelkey-ucd** [comment]
Incorporated [several of the fields listed](https://github.com/ucd-library/rp-ucd-client/blob/sandbox/client/public/src/models/CollectionModel.js#L38), but I couldn't find the following fields:

- Subject area (people)
- Journal title (I used the journal ID, which seems to have the title in it. But theres no dedicated title field)
- ISSN
- Work title for org
- Grant name for org

Let me know if these exist, and I'm just missing them in my dev setup.

**Comment by jrmerz** [comment]
@spelkey-ucd this is great! thanks.

If you want, here are the model definitions: https://wiki.lyrasis.org/display/VIVODOC110x/Ontology+Diagrams if you want to take a crack at mapping the above terms to the model terms.

**Comment by jrmerz** [comment]
@spelkey-ucd ignore the org files other than name.  As for the other fields:

- Subject area: hasResearchArea.label.text
- Journal title (for work): hasPublicationVenue.label.text
- Journal issn (for work): hasPublicationVenue.issn.text

about to push these updates to schema
