### ISSUE TITLE
Default search text fields need to be added

### ISSUE THREAD

**Issue by qjhart** [ucd-library/vessel#50]
Some ES fields, (eg. hasRessearchArea) need to have text fields added to them.

**Comment by qjhart** [comment]
@Vensberg, biggest change is that grant labels and sponsor numbers should be assigned to users results.  Sponsor names are *not*

**Comment by Vensberg** [comment]
It works for research areas, but not for grants belonging to a researcher. Example: "Human Movement and Sports Sciences". People result Fyhrie, David has his research area scored correctly. The search also brings grant result "CC-NIE Integration: Improved Infrastructure for Data Movement and Monitoring". Matt Bishop is on that grant. However, when you look at Matt's score (search results page 3), the grant is not showing up in his score.

**Comment by qjhart** [comment]
@Vensberg, yes it is: 
![image](https://user-images.githubusercontent.com/344953/155023746-1506a990-6cbb-4b93-8bdc-230bc773a9f5.png)

Simple test, search on `CC-NIE`

**Comment by Vensberg** [comment]
My bad, cache  again--will remember to clear before testing next time.
